name: build

on:
  push:
    branches:
      - master
  # schedule:
  #   # Every 10 hours
  #   - cron: '* */10 * * *'

# env:
  # These environments are used by the qt-installer.qs script
  # to login when installing Qt
  # QT_ACCOUNT_USERNAME: "my_qt_username"
  # QT_ACCOUNT_PASSWORD: "my_qt_password"

jobs:
  windows-build:
    timeout-minutes: 15
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create build directory
        shell: cmd
        run: mkdir build

      - name: Echo current dir
        working-directory: build
        shell: cmd
        run: cd

      - name: Install Qt
        working-directory: build
        shell: cmd
        run: |
          curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
          qt-unified-windows-x86-online.exe --verbose --script ..\ci\qt-installer.qs

      - name: Setup Qbs
        working-directory: build
        shell: cmd
        run: |
          Qt/Tools/QtCreator/bin/qbs.exe setup-toolchains --detect
          Qt/Tools/QtCreator/bin/qbs.exe setup-qt ./Qt/5.9.8/msvc2017_64/bin/qmake.exe qt-5-9-8

      - name: Compile and create installer
        working-directory: build
        shell: cmd
        run: |
          Qt/Tools/QtCreator/bin/qbs.exe build -p installer profile:qt-5-9-8 config:release
