name: build

on:
  push:
    branches:
      - 'master'
  schedule:
    # Every 10 hours
    - cron: '* */10 * * *'

env:
  QBS_DIR: Qt/Tools/QtCreator/bin/

jobs:
  windows-build:
    timeout-minutes: 15
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create build directory
        run: mkdir build

      - name: Install Qt
        working-directory: build
        run: |
          curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
          qt-unified-windows-x86-online.exe --verbose --script ..\ci\qt.qs

      - name: Setup Qbs
        working-directory: build
        run: |
          ./Qt/Tools/QtCreator/bin/qbs.exe setup-toolchains --detect
          ./Qt/Tools/QtCreator/bin/qbs.exe setup-qt ./Qt/5.9.8/msvc2017_64/bin/qmake.exe qt-5-9-8

      - name: Compile and create installer
        working-directory: build
        run: |
          ./Qt/Tools/QtCreator/bin/qbs.exe build -p installer profile:qt-5-9-8 config:release
